include: package:very_good_analysis/analysis_options.10.2.0.yaml

plugins:
  riverpod_lint: 3.1.2

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    avoid_catches_without_on_clauses: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    discarded_futures: false
    unreachable_from_main: false
    close_sinks: true

